language: python
env:
  # Region required, and Bypass credential lookup
  - AWS_DEFAULT_REGION="us-east-1" AWS_ACCESS_KEY_ID="some" AWS_SECRET_ACCESS_KEY="thing"
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - python setup.py develop
script: nosetests -s -v --with-coverage --cover-package=c7n tests
after_success:
  coveralls



