
# Image information for the Pod, default to the latest cloud custodian image
image:
  repository:  cloudcustodian/c7n
  tag: latest
  pullPolicy: Always

# Default values for environment variables. These are
# overrided by the values provided in subscriptionHost.environment
defaultEnvironment:
  AZURE_TENANT_ID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# Provide 1 or more sets of environment variables
# Each one will create a new deployment, each 
# targetting a subscription
subscriptionHosts:

  # All configuration for the Azure Container Host 
  # can be provided through environement variables.
  - name: "example-host"
    environment:
      AZURE_SUBSCRIPTION_ID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      AZURE_CLIENT_ID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      AZURE_CLIENT_SECRET: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      AZURE_CONTAINER_STORAGE: "https://storageAccount.blob.core.windows.net/policyContainerName"
      AZURE_EVENT_QUEUE_NAME: "example-event-queue"
      AZURE_EVENT_QUEUE_RESOURCE_ID: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/resourceGroupName/providers/Microsoft.Storage/storageAccounts/storageAccount"