trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

# Remap KV group variables to C7N env names
variables:
- group: AzureLiveTests
- name: AZURE_CLIENT_ID
  value: $(azure-client-id)
- name: AZURE_CLIENT_SECRET
  value: $(azure-client-secret)
- name: AZURE_TENANT_ID
  value: $(azure-tenant-id)
- name: AZURE_SUBSCRIPTION_ID
  value: $(azure-subscription-id)

jobs:
- job: 'azure_nightly_test_run'
  displayName: 'Azure Nightly Test Run'
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 0

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
    - checkout: self
      fetchDepth: 1

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        architecture: 'x64'

    - script: python -m pip install --upgrade pip && pip install . && pip install -r requirements-dev.txt
      displayName: "Install Dependencies"

    - script: az login --service-principal -u ${AZURE_CLIENT_ID} -p ${AZURE_CLIENT_SECRET} --tenant ${AZURE_TENANT_ID} && az account set -s ${AZURE_SUBSCRIPTION_ID}
      displayName: "Login to Azure"
      env:
        AZURE_CLIENT_ID: $(azure-client-id)
        AZURE_CLIENT_SECRET: $(azure-client-secret)
        AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
        AZURE_TENANT_ID: $(azure-tenant-id)

    # Skip some resources due to some restrictions with their provisioning using Service Principal account
    # We maintain those resources in the test subscription available for the tests
    - script: tools/c7n_azure/tests/templates/provision.sh --skip keyvault cost-management-export containerservice
      displayName: "Provision Azure Resources"
      env:
        AZURE_CLIENT_ID: $(azure-client-id)
        AZURE_CLIENT_SECRET: $(azure-client-secret)

    - script: C7N_TEST_RUN=true C7N_FUNCTIONAL=yes pytest tools/c7n_azure/tests
      displayName: "Run Azure tests without cassettes"

    - script: tools/c7n_azure/tests/templates/cleanup.sh --skip keyvault cost-management-export containerservice
      displayName: "Cleanup Azure Resources"
      condition: always()
